Web/ChooseAndBuy.Web/Controllers/OrdersController.cs
namespace ChooseAndBuy.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using ChooseAndBuy.Common;
    using ChooseAndBuy.Data.Models;
    using ChooseAndBuy.Services;
    using ChooseAndBuy.Web.BindingModels.Addresses;
    using ChooseAndBuy.Web.ViewModels.Administration.Orders;
    using ChooseAndBuy.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class OrdersController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICityService cityService;
        private readonly IShoppingCartService shoppingCartService;
        private readonly IAddressService addressService;
        private readonly IOrderService orderService;

        public OrdersController(
            UserManager<ApplicationUser> userManager,
            ICityService cityService,
            IShoppingCartService shoppingCartService,
            IAddressService addressService,
            IOrderService orderService)
        {
            this.userManager = userManager;
            this.cityService = cityService;
            this.shoppingCartService = shoppingCartService;
            this.addressService = addressService;
            this.orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var cities = await this.cityService.GetAllCities();

            var userAddresses = await this.addressService.GetAllUserAddresses(user.Id);

            var cartProducts = await this.shoppingCartService.GetCartProductsByUserId(user.Id);

            // If there are no products in the cart the user will be redirected
            if (cartProducts.Count() == 0)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var totalPrice = cartProducts.Sum(p => p.TotalPrice) + GlobalConstants.DeliveryFee;

            AddressCreateBindingModel addressBindingModel = new AddressCreateBindingModel
            {
                PhoneNumber = user.PhoneNumber,
                Cities = cities,
            };

            OrderBindingModel orderBindingModel = new OrderBindingModel
            {
                Products = cartProducts.ToList(),
                ApplicationUserId = user.Id,
                TotalPrice = totalPrice,
                DeliveryFee = GlobalConstants.DeliveryFee,
            };

            CheckoutViewModel model = new CheckoutViewModel
            {
                AddressCreate = addressBindingModel,
                UserAddresses = userAddresses.ToList(),
                OrderCreate = orderBindingModel,
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderBindingModel orderCreate)
        {
            // creates the order and recieves it's id
            var orderId = await this.orderService.CreateOrder(orderCreate);

            // add the order products to the order
            await this.orderService.AddProductsToOrder(orderId, orderCreate.Products);

            // remove the products from the shopping cart after the order is added
            await this.shoppingCartService.RemoveAllCartProducts(orderCreate.ApplicationUserId);

            return this.RedirectToAction("Confirmation", new { orderId = orderId });
        }

        [HttpGet]
        public async Task<IActionResult> Confirmation(string orderId)
        {
            var model = await this.orderService.GetConfirmationInfo(orderId);

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> UserOrders()
        {
            string userId = this.userManager.GetUserId(this.HttpContext.User);

            var ordersViewModel = await this.orderService.GetAllUserOrders(userId);

            UserOrderViewModel model = new UserOrderViewModel
            {
                Orders = ordersViewModel.ToList(),
            };

            return this.View(model);
        }
    }
}

Web/ChooseAndBuy.Web/Controllers/ProductsController.cs
namespace ChooseAndBuy.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using ChooseAndBuy.Common;
    using ChooseAndBuy.Services;
    using ChooseAndBuy.Web.BindingModels.Products;
    using ChooseAndBuy.Web.ViewModels.Products;
    using Microsoft.AspNetCore.Mvc;
    using X.PagedList;

    public class ProductsController : BaseController
    {
        private readonly ICategoryService categoryService;
        private readonly IProductService productsService;
        private readonly IReviewService reviewService;

        public ProductsController(
            ICategoryService categoryService,
            IProductService productsService,
            IReviewService reviewService)
        {
            this.categoryService = categoryService;
            this.productsService = productsService;
            this.reviewService = reviewService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(ProductsViewModel model)
        {
            var page = model.PageNum ?? GlobalConstants.DefaultProductsPage;
            var show = model.ShowNum ?? GlobalConstants.DefaultProductsShow;
            var sortBy = model.SortBy ?? GlobalConstants.DefaultProductsSorting;

            var products = await this.productsService.GetProducts(model.Search, model.SubCategoryId, sortBy);

            var pagedProducts = products.ToPagedList(page, show);

            model.Categories = await this.categoryService.GetCategoriesWithSubCategories();
            model.Products = pagedProducts;

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string term)
        {
            var products = this.productsService.GetSearchedProducts(term);

            if (products.Count() == 0)
            {
                return this.Json(new List<SearchViewModel>
                {
                    new SearchViewModel
                    {
                        Value = GlobalConstants.SearchNoResults,
                        Url = string.Empty,
                    },
                });
            }

            var result = products.Select(x => new SearchViewModel
            {
                Value = x.Name,
                Url = GlobalConstants.ProductDetailsUrl + x.Id,
            });

            return this.Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var detailsInfo = await this.productsService.GetById(id);

            detailsInfo.Reviews = await this.reviewService.GetReviewsForProduct(id);

            var recommendedProducts = await this.productsService.GetRecommendationProducts();

            AllDetailsViewModel productModel = new AllDetailsViewModel
            {
                DetailsInfo = detailsInfo,
                ReviewModel = new ReviewBindingModel { ProductId = id },
                RecommendedProducts = recommendedProducts.ToList(),
            };

            return this.View(productModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddReview(ReviewBindingModel productModel)
        {
            await this.reviewService.AddReview(productModel);

            return this.RedirectToAction("Details", new { id = productModel.ProductId });
        }
    }
}

Web/ChooseAndBuy.Web/Controllers/ShoppingCartController.cs
namespace ChooseAndBuy.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using ChooseAndBuy.Data.Models;
    using ChooseAndBuy.Services;
    using ChooseAndBuy.Web.BindingModels.ShoppingCart;
    using ChooseAndBuy.Web.ViewModels.ShoppingCart;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class ShoppingCartController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;
        private readonly UserManager<ApplicationUser> userManager;

        public ShoppingCartController(
            IShoppingCartService shoppingCartService,
            UserManager<ApplicationUser> userManager)
        {
            this.shoppingCartService = shoppingCartService;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (this.User.Identity.IsAuthenticated)
            {
                string userId = this.userManager.GetUserId(this.HttpContext.User);
                var products = await this.shoppingCartService.GetCartProductsByUserId(userId);

                var mappedProducts = AutoMapper.Mapper.Map<List<ShoppingCartProductViewModel>>(products);

                var model = new ShoppingCartViewModel
                {
                    Products = mappedProducts,
                    TotalPrice = mappedProducts.Sum(x => x.TotalPrice),
                };

                return this.View(model);
            }

            var sessionCart = this.shoppingCartService.GetOrCreateSessionCart(this.HttpContext.Session);

            return this.View(sessionCart);
        }

        [HttpPost]
        public async Task<IActionResult> Add([FromBody]ShoppingCartAddInputModel model)
        {
            string userId = this.userManager.GetUserId(this.HttpContext.User);
            bool result = false;

            if (this.User.Identity.IsAuthenticated)
            {
                result = await this.shoppingCartService.AddProductToCart(model.ProductId, userId, model.Quantity);

                return this.Json(result);
            }

            result = await this.shoppingCartService
                .AddProductToSessionCart(this.HttpContext.Session, model.ProductId, model.Quantity);

            return this.Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductCount(ShoppingCartUpdateCountBindingModel model)
        {
            if (this.User.Identity.IsAuthenticated)
            {
                string userId = this.userManager.GetUserId(this.HttpContext.User);

                await this.shoppingCartService.UpdateProductCount(model.ProductId, userId, model.Quantity);

                return this.RedirectToAction("Index");
            }

            // this prevents the product in the cart to be with 0 quantity.
            if (model.Quantity == 0)
            {
                return this.RedirectToAction("Index");
            }

            await this.shoppingCartService
                .UpdateSessionProductCount(this.HttpContext.Session, model.ProductId, model.Quantity);

            return this.RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Remove(string productId)
        {
            bool result = false;

            if (this.User.Identity.IsAuthenticated)
            {
                string userId = this.userManager.GetUserId(this.HttpContext.User);

                result = await this.shoppingCartService.RemoveProductFromCart(productId, userId);

                return this.Json(result);
            }

            result = await this.shoppingCartService.RemoveProductFromSessionCart(this.HttpContext.Session, productId);

            return this.Json(result);
        }
    }
}

Web/ChooseAndBuy.Web/Views/ShoppingCart/Index.cshtml
@using ChooseAndBuy.Web.ViewModels.ShoppingCart

@model ShoppingCartViewModel

@{
    ViewData["Title"] = "Shopping Cart";
}

<!--================Cart Area =================-->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var product in Model.Products)
                        {
                            <tr id="@product.Id">
                                <td class="">
                                    <div class="media">
                                        <div style="height: 130px; width: 130px;">
                                            <img src="@product.ImageName" style="max-height: 130px; max-width: 130px;" alt="">
                                        </div>
                                        <div class="media-body">
                                            <h4 class="text-primary ml-5">
                                                <a asp-action="details" asp-controller="products" asp-route-id="@product.Id" asp-area="">
                                                    @product.Name
                                                </a>
                                            </h4>
                                        </div>
                                    </div>
                                </td>
                                <td class="">
                                    <h5>$@product.Price</h5>
                                </td>
                                <td class="">
                                    <div class="product_count">
                                        <a>

                                        </a>
                                        <input type="text" name="qty" id="sst" maxlength="12" value="@product.Quantity" title="Quantity:"
                                               class="input-text qty">
                                        <form method="post">
                                            <button asp-controller="ShoppingCart" asp-action="UpdateProductCount" asp-route-ProductId="@product.Id" asp-route-Quantity="@(product.Quantity + 1)"
                                                    class="increase items-count" type="submit">
                                                <i class="lnr lnr-chevron-up"></i>
                                            </button>
                                            <button asp-controller="ShoppingCart" asp-action="UpdateProductCount" asp-route-ProductId="@product.Id" asp-route-Quantity="@(product.Quantity - 1)"
                                                    class="reduced items-count" type="submit">
                                                <i class="lnr lnr-chevron-down"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                                <td class="">
                                    <h5>$@product.TotalPrice</h5>
                                </td>
                                <td class="">
                                    <a id="@product.Id" accesskey="@product.TotalPrice" class="removeProduct genric-btn danger radius text-dark">
                                        Remove
                                    </a>
                                </td>
                            </tr>
                        }
                        <tr>
                            <td></td>
                            <td></td>
                            <td>
                                @if (Model.TotalPrice == 0)
                                {
                                    <h5>Your cart is empty</h5>
                                }
                                else
                                {
                                    <h5>Subtotal</h5>
                                }
                            </td>
                            <td>
                                <h5 class="totalP" id="@Model.TotalPrice">$@Model.TotalPrice</h5>
                            </td>
                            <td></td>
                        </tr>
                        <tr class="out_button_area">
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>
                                <div class="checkout_btn_inner d-flex align-items-center">
                                    @if (this.User.Identity.IsAuthenticated)
                                    {
                                        @if (Model.TotalPrice == 0)
                                        {
                                            <a asp-action="Index" asp-controller="Products" class="gray_btn">Continue Shopping</a>
                                        }
                                        else
                                        {
                                            <a asp-action="Index" asp-controller="Products" class="gray_btn">Continue Shopping</a>
                                            <a class="primary-btn" id="checkoutBtn" asp-action="Index" asp-controller="Orders">Proceed to checkout</a>
                                        }
                                    }
                                    else
                                    {
                                        <a asp-area="Identity" asp-page="/Account/Login" asp-route-returnUrl="/ShoppingCart/Index/" class="gray_btn">Login to Make Orders</a>
                                    }

                                </div>
                            </td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!--================End Cart Area =================-->
@section Scripts {
    <script src="~/js/shoppingCart.js"></script>
}