Web/ChooseAndBuy.Web/Areas/Administration/Controllers/OrdersController.cs
namespace ChooseAndBuy.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using ChooseAndBuy.Services;
    using ChooseAndBuy.Web.BindingModels.Orders;
    using ChooseAndBuy.Web.ViewModels.Administration.Orders;
    using Microsoft.AspNetCore.Mvc;

    public class OrdersController : AdministrationController
    {
        private readonly IOrderService orderService;

        public OrdersController(
            IOrderService orderService)
        {
            this.orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> PendingOrders()
        {
            var orders = await this.orderService.GetPendingOrders();

            AdminPaneOrdersViewModel model = new AdminPaneOrdersViewModel
            {
                Orders = orders.ToList(),
            };

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ActiveOrders()
        {
            var orders = await this.orderService.GetActiveOrders();

            AdminPaneOrdersViewModel model = new AdminPaneOrdersViewModel
            {
                Orders = orders.ToList(),
                ReasonModel = new ReturnReasonBindingModel(),
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Return(ReturnReasonBindingModel reasonModel)
        {
            var result = await this.orderService.ReturnOrder(reasonModel.OrderId, reasonModel.ReturnReason);

            return this.RedirectToAction("ActiveOrders");
        }

        [HttpPost]
        public async Task<IActionResult> Approve(string orderId)
        {
            var result = await this.orderService.ApproveOrder(orderId);

            return this.Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> Deliver(string orderId)
        {
            var orderIdCut = orderId;

            var result = await this.orderService.DeliverOrder(orderIdCut);

            return this.Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(string orderId)
        {
            var orderIdCut = orderId;

            var result = await this.orderService.CancelOrder(orderIdCut);

            return this.Json(result);
        }
    }
}

Web/ChooseAndBuy.Web/Controllers/AddressesController.cs
namespace ChooseAndBuy.Web.Controllers
{
    using System.Threading.Tasks;

    using ChooseAndBuy.Data.Models;
    using ChooseAndBuy.Services;
    using ChooseAndBuy.Web.BindingModels.Addresses;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class AddressesController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IAddressService addressService;

        public AddressesController(
            UserManager<ApplicationUser> userManager,
            IAddressService addressService)
        {
            this.userManager = userManager;
            this.addressService = addressService;
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddressCreateBindingModel addressCreate)
        {
            string userId = this.userManager.GetUserId(this.HttpContext.User);

            await this.addressService.CreateAddress(addressCreate, userId);

            return this.RedirectToAction("Index", "Orders");
        }
    }
}

Web/ChooseAndBuy.Web/Controllers/OrdersController.cs
namespace ChooseAndBuy.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using ChooseAndBuy.Common;
    using ChooseAndBuy.Data.Models;
    using ChooseAndBuy.Services;
    using ChooseAndBuy.Web.BindingModels.Addresses;
    using ChooseAndBuy.Web.ViewModels.Administration.Orders;
    using ChooseAndBuy.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class OrdersController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICityService cityService;
        private readonly IShoppingCartService shoppingCartService;
        private readonly IAddressService addressService;
        private readonly IOrderService orderService;

        public OrdersController(
            UserManager<ApplicationUser> userManager,
            ICityService cityService,
            IShoppingCartService shoppingCartService,
            IAddressService addressService,
            IOrderService orderService)
        {
            this.userManager = userManager;
            this.cityService = cityService;
            this.shoppingCartService = shoppingCartService;
            this.addressService = addressService;
            this.orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var cities = await this.cityService.GetAllCities();

            var userAddresses = await this.addressService.GetAllUserAddresses(user.Id);

            var cartProducts = await this.shoppingCartService.GetCartProductsByUserId(user.Id);

            // If there are no products in the cart the user will be redirected
            if (cartProducts.Count() == 0)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var totalPrice = cartProducts.Sum(p => p.TotalPrice) + GlobalConstants.DeliveryFee;

            AddressCreateBindingModel addressBindingModel = new AddressCreateBindingModel
            {
                PhoneNumber = user.PhoneNumber,
                Cities = cities,
            };

            OrderBindingModel orderBindingModel = new OrderBindingModel
            {
                Products = cartProducts.ToList(),
                ApplicationUserId = user.Id,
                TotalPrice = totalPrice,
                DeliveryFee = GlobalConstants.DeliveryFee,
            };

            CheckoutViewModel model = new CheckoutViewModel
            {
                AddressCreate = addressBindingModel,
                UserAddresses = userAddresses.ToList(),
                OrderCreate = orderBindingModel,
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderBindingModel orderCreate)
        {
            // creates the order and recieves it's id
            var orderId = await this.orderService.CreateOrder(orderCreate);

            // add the order products to the order
            await this.orderService.AddProductsToOrder(orderId, orderCreate.Products);

            // remove the products from the shopping cart after the order is added
            await this.shoppingCartService.RemoveAllCartProducts(orderCreate.ApplicationUserId);

            return this.RedirectToAction("Confirmation", new { orderId = orderId });
        }

        [HttpGet]
        public async Task<IActionResult> Confirmation(string orderId)
        {
            var model = await this.orderService.GetConfirmationInfo(orderId);

            return this.View(model);
        }

        [HttpGet]
        public async Task<IActionResult> UserOrders()
        {
            string userId = this.userManager.GetUserId(this.HttpContext.User);

            var ordersViewModel = await this.orderService.GetAllUserOrders(userId);

            UserOrderViewModel model = new UserOrderViewModel
            {
                Orders = ordersViewModel.ToList(),
            };

            return this.View(model);
        }
    }
}

Web/ChooseAndBuy.Web/Views/Orders/Confirmation.cshtml
@using ChooseAndBuy.Web.ViewModels.Orders

@model  ConfirmationViewModel

@{
    ViewData["Title"] = "Confirmation";
}

<!--================Order Details Area =================-->
<section class="order_details section_gap">
    <div class="container">
        <h3 class="title_confirmation">Thank you. Your order has been received.</h3>
        <div class="row order_d_inner">
            <div class="col-lg-12">
                <div class="details_item">
                    <h4 class="text-center">Order Info</h4>
                    <div class="d-flex justify-content-center">
                        <ul class="list order_box">
                            <li><a href="#"><span>Expected delivery</span> : @Model.ExpectedDelivery</a></li>
                            <li><a href="#"><span>Payment method</span> : @Model.PaymentMethod</a></li>
                            <li><a href="#"><span>Quantity of products</span> : @Model.QuantityProducts</a></li>
                            <li><a href="#"><span>Total price</span> : $@Model.TotalPrice</a></li>
                        </ul>
                        <ul class="list order_box">
                            <li><a href="#"><span>Client Name</span> : @Model.ClientName</a></li>
                            <li><a href="#"><span>City</span> : @Model.City</a></li>
                            <li><a href="#"><span>Address</span> : @Model.Address</a></li>
                            <li><a href="#"><span>Phone Number</span> : @Model.PhoneNumber</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Order Details Area =================-->

Web/ChooseAndBuy.Web/Views/Orders/Index.cshtml
@using ChooseAndBuy.Web.ViewModels.Orders

@model CheckoutViewModel

@{
    ViewData["Title"] = "Checkout";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<!--================Checkout Area =================-->
<section class="checkout_area section_gap">
    <div class="container">
        <div class="billing_details">
            <!--================Start Address Create Modal Area =================-->
            <div class="modal fade" id="crtWindow">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Create Address</h4>
                        </div>
                        <div class="modal-body">
                            <form class="" method="post" asp-action="Add" asp-controller="Addresses">
                                <div class="row">
                                    <div class="col-md-6 form-group p_star">
                                        <label asp-for="AddressCreate.FirstName" class="float-left"></label>
                                        <input asp-for="AddressCreate.FirstName" type="text" class="form-control">
                                        <span asp-validation-for="AddressCreate.FirstName" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-6 form-group p_star">
                                        <label asp-for="AddressCreate.LastName" class="float-left"></label>
                                        <input asp-for="AddressCreate.LastName" type="text" class="form-control">
                                        <span asp-validation-for="AddressCreate.LastName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="AddressCreate.AddressText" class="float-left"></label>
                                    <textarea asp-for="AddressCreate.AddressText" class="form-control"></textarea>
                                    <span asp-validation-for="AddressCreate.AddressText" class="text-danger"></span>
                                </div>
                                <div class="form-group"><p><strong>Note:</strong> You can change your default phone number in your account page.</p></div>
                                <div class="row">
                                    <div class="col-md-7 form-group">
                                        <label asp-for="AddressCreate.PhoneNumber" class="float-left"></label>
                                        <input asp-for="AddressCreate.PhoneNumber" type="tel" class="form-control" placeholder="Your Phone Number">
                                        <span asp-validation-for="AddressCreate.PhoneNumber" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-4 form-group">
                                        <label asp-for="AddressCreate.CityId" class="float-left"></label>
                                        <div class="country_select" id="default-select">
                                            <select asp-for="AddressCreate.CityId" class="default-select" asp-items="@Model.AddressCreate.Cities"></select>
                                        </div>
                                        <span asp-validation-for="AddressCreate.CityId" class="text-danger"></span>
                                    </div>
                                </div>
                                <button class="primary-btn mt-3 text-center" type="submit" value="submit">Create Address</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--================End Address Create Modal Area =================-->
            <div class="row mt-3">
                <!--================Start Order Details =================-->
                <div class="col-lg-8 order_box">
                    <h3>Order Details</h3>
                    <form class="row contact_form" asp-action="Create" asp-controller="Orders" method="post">
                        <input asp-for="OrderCreate.ApplicationUserId" type="hidden" />
                        @for (int i = 0; i < Model.OrderCreate.Products.Count(); i++)
                        {
                            <input asp-for="OrderCreate.Products[i].ProductId" type="hidden" />
                            <input asp-for="OrderCreate.Products[i].Name" type="hidden" />
                            <input asp-for="OrderCreate.Products[i].Price" type="hidden" />
                            <input asp-for="OrderCreate.Products[i].Quantity" type="hidden" />
                            <input asp-for="OrderCreate.Products[i].TotalPrice" type="hidden" />
                        }
                        <input asp-for="OrderCreate.TotalPrice" type="hidden" />
                        <input asp-for="OrderCreate.DeliveryFee" type="hidden" />
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col">
                                    <h5>My Addresses</h5>
                                </div>
                                <div class="col float-right">
                                    <button id="crtAddress" type="button" class="btn-primary float-right">Create Address</button>
                                </div>
                            </div>
                            <table class="table mt-3">
                                <tbody>
                                    @foreach (var address in Model.UserAddresses)
                                    {
                                        <tr>
                                            <td>
                                                <h6 class="text-primary">@address.AddressText</h6>
                                            </td>
                                            <td><input asp-for="OrderCreate.DeliveryAddressId" type="radio" value="@address.Id" /></td>
                                        </tr>
                                    }
                                    <span asp-validation-for="OrderCreate.DeliveryAddressId" class="text-danger"></span>
                                </tbody>
                            </table>

                        </div>
                        <div class="col-md-12 form-group">
                            <label asp-for="OrderCreate.AdditionalInfo" class="float-left"></label>
                            <textarea asp-for="OrderCreate.AdditionalInfo" class="form-control"></textarea>
                            <span asp-validation-for="OrderCreate.AdditionalInfo" class="text-danger"></span>
                        </div>
                        <div class="col">
                            <div class="col-4 form-group p_star">
                                <label asp-for="OrderCreate.PaymentType" class="float-left"></label>
                                <select asp-for="OrderCreate.PaymentType" asp-items="Html.GetEnumSelectList<ChooseAndBuy.Data.Models.Enums.PaymentType>()"></select>
                                <span asp-validation-for="OrderCreate.PaymentType" class="text-danger"></span>
                            </div>
                            <div class="col-4 form-group p_star">
                                <label asp-for="OrderCreate.DeliveryType" class="float-left"></label>
                                <select asp-for="OrderCreate.DeliveryType" asp-items="Html.GetEnumSelectList<ChooseAndBuy.Data.Models.Enums.DeliveryType>()"></select>
                                <span asp-validation-for="OrderCreate.DeliveryType" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <table class="table mt-3">
                                <thead>
                                    <tr>
                                        <th scope="col">Products</th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var product in Model.OrderCreate.Products)
                                    {
                                        <tr>
                                            <td>
                                                <h6 class="text-primary">@product.Name</h6>
                                            </td>
                                            <td>@("x" + product.Quantity)</td>
                                            <td>$@product.TotalPrice</td>
                                        </tr>
                                    }
                                    <tr>
                                        <td>Delivery Fee</td>
                                        <td></td>
                                        <td>+$@Model.OrderCreate.DeliveryFee</td>
                                    </tr>
                                    <tr class="PriceSum">
                                        <td><strong>TOTAL</strong></td>
                                        <td></td>
                                        <td><strong>$@Model.OrderCreate.TotalPrice</strong></td>
                                    </tr>
                                    <tr></tr>
                                </tbody>
                            </table>
                            <button class="primary-btn" type="submit">Proceed</button>
                        </div>
                    </form>
                </div>
                <!--================End Order Details =================-->
                <!--================Start Side Bar (Terms and Conditions) =================-->
                <div class="col-lg-4">
                    <div class="order_box">
                        <h4>Terms and Conditions</h4>
                        <p>
                            By accessing this website we assume you accept these terms and conditions in full. Do not continue to use Choose And Buy's website
                            if you do not accept all of the terms and conditions stated on this page.
                        </p>
                        <p>
                            The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice
                            and any or all Agreements: "Client", "You" and "Your" refers to you, the person accessing this website
                            and accepting the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers
                            to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves, or either the Client
                            or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake
                            the process of our assistance to the Client in the most appropriate manner, whether by formal meetings
                            of a fixed duration, or any other means, for the express purpose of meeting the Client's needs in respect
                            of provision of the Company's stated services/products, in accordance with and subject to, prevailing law
                            of . Any use of the above terminology or other words in the singular, plural,
                            capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same. Read more <a asp-action="Privacy" asp-controller="Home">here.</a>
                    </div>
                </div>
                <!--================End Side Bar (Terms and Conditions) =================-->
            </div>
        </div>
    </div>
</section>
<!--================End Checkout Area =================-->

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#crtAddress").click(function () {
                $("#crtWindow").modal('show');
            });
        });
    </script>
    <partial name="_ValidationScriptsPartial" />
}

Web/ChooseAndBuy.Web/Views/Orders/UserOrders.cshtml
@using ChooseAndBuy.Web.ViewModels.Orders

@model UserOrderViewModel

@{
    ViewData["Title"] = "My Orders";
}

<!-- Start Table Area -->
<section class="cart_area">
    <div class="container">
        <div class="cart_inner">
            <div class="login-form">
                <table class="table">
                    <h3 class="text-center">My Orders</h3>
                    <hr style="height: 3px" />
                    <thead>
                        <tr>
                            <th scope="col">Address</th>
                            <th scope="col">Expected Delivery</th>
                            <th scope="col">Status</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var order in Model.Orders)
                        {
                            <tr>
                                <td class="text-primary">@order.Address</td>
                                <td>@order.ExpectedDelivery.ToShortDateString()</td>
                                <td>@order.Status</td>
                                <td>@order.Quantity</td>
                                <td>$@order.Price</td>
                                <td>
                                    <a asp-action="OrderDetails" asp-controller="Orders" asp-route-productId="@order.Id"
                                       id="details-@order.Id" class="genric-btn primary radius text-dark" data-toggle="modal" data-target="#modal-@order.Id">
                                        View Details
                                    </a>
                                </td>
                                <!-- Start Details Modal Area -->
                                <div class="modal fade bd-example-modal-lg" id="modal-@order.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-lg" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Order Details</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">
                                                    <div class="col-sm-7">
                                                        <h5>Details</h5>
                                                        <hr style="height: 3px" />
                                                        <dl class="row">
                                                            <dt class="col-sm-4">Order Status</dt>
                                                            <dd class="col-sm-8">@order.Status</dd>
                                                            <dt class="col-sm-4">Products Quantity</dt>
                                                            <dd class="col-sm-8">x@(order.Quantity)</dd>
                                                            <dt class="col-sm-4">Total Price</dt>
                                                            <dd class="col-sm-8">$@order.Price</dd>
                                                            <dt class="col-sm-4">Payment Method</dt>
                                                            <dd class="col-sm-8">@order.PaymentType</dd>
                                                            <dt class="col-sm-4">Delivery Option</dt>
                                                            <dd class="col-sm-8">@order.DeliveryType</dd>
                                                            <dt class="col-sm-4">Order Date</dt>
                                                            <dd class="col-sm-8">@order.OrderDate</dd>
                                                            <dt class="col-sm-4">Delivery Date</dt>
                                                            @if (order.Status == "Delivered")
                                                            {
                                                                <dd class="col-sm-8">@order.DeliveryDate.Value.ToShortDateString()</dd>
                                                            }
                                                            else if (order.Status == "Canceled" || order.Status == "Returned")
                                                            {
                                                                <dd class="col-sm-8">-</dd>
                                                            }
                                                            else
                                                            {
                                                                <dd class="col-sm-8" id="deliveryDate-@order.Id">In proccess</dd>
                                                            }
                                                        </dl>
                                                    </div>
                                                    <div class="col-sm-5">
                                                        <h5>Products</h5>
                                                        <hr style="height: 3px" />
                                                        <dl class="row">
                                                            @foreach (var product in order.Products)
                                                            {
                                                                <dt class="col-9">@product.Name</dt>
                                                                <dd class="col-3">x@(product.Quantity)</dd>
                                                            }
                                                        </dl>
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Start Details Modal Area -->
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!--================End Table Area =================-->